GET http://localhost:5015/anime
###
POST http://localhost:5015/anime
Content-Type: application/json

{
    "title": "Naruto",
    "description": "A story about a young ninja.",
    "releaseDate": "2002-10-03T00:00:00Z",
    "genreId": 1

}
###
POST http://localhost:5015/anime
Content-Type: application/json

{
    "title": "One Piece",
    "description": "A story about pirates.",
    "releaseDate": "1999-10-20T00:00:00Z",
    "genreId": 1

}
###
GET http://localhost:5015/anime/3