GET http://localhost:5015/anime
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYm9iIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc1OTIzMzM2MSwiaXNzIjoiQW5pbWVFbmN5Y2xvcGVkaWEiLCJhdWQiOiJBbmltZUVuY3ljbG9wZWRpYSJ9.3ITgGc1MeNdWo0vRmlkW9jf-B_AgkLE_YFMEMvDqQDs
###
POST http://localhost:5015/anime
Content-Type: application/json

{
    "title": "Naruto",
    "description": "A story about a young ninja.",
    "releaseDate": "2002-10-03T00:00:00Z",
    "genreId": 1

}
###
POST http://localhost:5015/anime
Content-Type: application/json

{
    "title": "Bleach",
    "description": "A story about a high school student who becomes a Soul Reaper.",
    "releaseDate": "2004-10-05T00:00:00Z",
    "genreId": 1

}
###
GET http://localhost:5015/anime/5
###
PUT http://localhost:5015/anime/3
Content-Type: application/json

{
    "title": "Naruto",
    "description": "A story about a young ninja. His dream is to become the Hokage.",
    "releaseDate": "2002-10-03T00:00:00Z",
    "genreId": 1
}
###
DELETE http://localhost:5015/anime/7
###
GET http://localhost:5015/genres
###
POST http://localhost:5015/genres
Content-Type: application/json

{
    "name": "Romance"
}
###
GET http://localhost:5015/anime/3/characters
###
POST http://localhost:5015/anime/3/characters
Content-Type: application/json

{
    "name": "Sasuke Uchiha",
    "role": "Main Character"
}
###
POST http://localhost:5015/auth/register
Content-Type: application/json

{
    "username": "bob",
    "email":"b@x",
    "password": "P@ss1234"
}
###
POST http://localhost:5015/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "bob",
  "password": "P@ss1234"
}
###
POST http://localhost:5015/auth/revoke
Content-Type: application/json

{
  "refreshToken": "sl4OUEoYmSIFJv+vaCadgmKgPskwLoOssfEy0UTDsIGYy9nthlXrjkgl3tmFUp7fpcpxqdDg4JNX9Evmi+xMUQ=="
}
###
GET http://localhost:5015/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYm9iIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc1OTIzMzM2MSwiaXNzIjoiQW5pbWVFbmN5Y2xvcGVkaWEiLCJhdWQiOiJBbmltZUVuY3ljbG9wZWRpYSJ9.3ITgGc1MeNdWo0vRmlkW9jf-B_AgkLE_YFMEMvDqQDs
###
GET http://localhost:5015/anime
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYm9iIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc1OTMxNTI1MywiaXNzIjoiQW5pbWVFbmN5Y2xvcGVkaWEiLCJhdWQiOiJBbmltZUVuY3ljbG9wZWRpYSJ9.SI4HF4FPUASQ3GtJC-1YPTcJCBbs5mQ0vfpO5aDcgHw
###
GET http://localhost:5015/test-error